### ISSUE TITLE
External relation crete error

### ISSUE THREAD

**Issue by cybersmurf** [mirekmarek/php-jet#4]
Afert Select related DataModel:

i see this error

script: | C:\MAMP\htdocs\_tools\studio\application\Classes\DataModel\Definition\Relation\External.php
-- | --
line: | 148
time: | 2022-11-01 15:36:02
URL: | localhost/_tools/studio/data_model.php?class=JetApplication/data_model.php?class=JetApplication%5Czakazka&action=relation%2Fadd_form&related_model=JetApplication\zakaznik

![image](https://user-images.githubusercontent.com/3642214/199259695-09028dcf-1926-41ba-b1d3-a4859a1fee64.png)

**Comment by mirekmarek** [comment]
Thanks for reporting!
It seems to be a problem when running on Windows.
I have a solution but I need to test it. Patience please, I need to virtualize Windows ;-)

**Comment by mirekmarek** [comment]
Dík :-) 
Pokud to testnete na Windows budu Vám vděčný.
Je o skript:
~/_tools/studio/application/config/URI.php

Toto:
$base_URI = dirname($base_URI).'/';

Je nutné nahradit tímto:
$base_URI = substr( $base_URI, 0, strrpos($base_URI, '/')).'/';

Děkuji uctivě :-)

**Comment by cybersmurf** [comment]
tak na windows to zafungovalo :)

už to běží

út 1. 11. 2022 v 16:54 odesílatel Mirek Marek ***@***.***>
napsal:

**Comment by mirekmarek** [comment]
Díky moc za spolupráci! 

Ať se daří
Mirek
